// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNF-_575zgl2pN_A-kWX_D6U1AxeHj0Vc',
    appId: '1:83939725208:web:f642dbe46da41f4244a5ed',
    messagingSenderId: '83939725208',
    projectId: 'ahassu',
    authDomain: 'ahassu.firebaseapp.com',
    storageBucket: 'ahassu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA60GvMUGMWSB_cfACXhEZtH3Lrgs4WAIQ',
    appId: '1:83939725208:android:4bd742666e01a39944a5ed',
    messagingSenderId: '83939725208',
    projectId: 'ahassu',
    storageBucket: 'ahassu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmCDM6ZANvSzl-EtLChK1yso9us5_g82s',
    appId: '1:83939725208:ios:3660f7731a2c760244a5ed',
    messagingSenderId: '83939725208',
    projectId: 'ahassu',
    storageBucket: 'ahassu.firebasestorage.app',
    iosBundleId: 'com.ahassu.ahassu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmCDM6ZANvSzl-EtLChK1yso9us5_g82s',
    appId: '1:83939725208:ios:3660f7731a2c760244a5ed',
    messagingSenderId: '83939725208',
    projectId: 'ahassu',
    storageBucket: 'ahassu.firebasestorage.app',
    iosBundleId: 'com.ahassu.ahassu',
  );
}
